# Generated by Django 5.0.7 on 2024-07-10 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consumers', '0001_initial'),
        ('refill_centers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CylinderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cylinder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('empty', 'Empty'), ('full', 'Full')], max_length=10)),
                ('location', models.CharField(max_length=255)),
                ('consumer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consumers.consumer')),
                ('refill_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='refill_centers.refillcenter')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cylinders.cylindertype')),
            ],
        ),
    ]
